# Generated by Django 4.2.1 on 2023-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
