# Generated by Django 4.2.1 on 2023-06-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
