# Generated by Django 4.2.1 on 2023-06-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0008_order_is_cancelled_order_is_confirmed_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomapp.order')),
            ],
        ),
    ]
